import { supabase } from '../src/integrations/supabase/client';
import { Department, CSPFormData, CSPRequest, RequestStatus } from '../types';

const STORAGE_BUCKET = 'uploads'; // Nome do bucket centralizado
const TABLE_NAME = 'payment_requests';
const PLACEHOLDER_UUID = '00000000-0000-0000-0000-000000000000';

// Fetch Departments from Supabase
export const fetchDepartments = async (): Promise<Department[]> => {
  const { data, error } = await supabase
    .from('departments')
    .select('id, name, is_active')
    .eq('is_active', true)
    .order('name');

  if (error) {
    console.error('Error fetching departments:', error);
    return [];
  }

  return data.map(d => ({
    id: d.id,
    name: d.name,
    active: d.is_active
  }));
};

// Fetch Authorizers from Supabase
export const fetchAuthorizers = async (): Promise<{ id: string; name: string }[]> => {
  const { data, error } = await supabase
    .from('authorizers')
    .select('id, name')
    .eq('is_active', true);

  if (error) {
    console.error('Error fetching authorizers:', error);
    return [];
  }

  return data.map(a => ({ id: a.id, name: a.name }));
};

// Fetch Payment Accounts from Supabase
export const fetchPaymentAccounts = async (): Promise<{ id: string; label: string }[]> => {
  const { data, error } = await supabase
    .from('payment_accounts')
    .select('id, label')
    .eq('is_active', true)
    .order('label');

  if (error) {
    console.error('Error fetching accounts:', error);
    return [];
  }

  return data.map(a => ({ id: a.id, label: a.label }));
};

/**
 * Upload File to Supabase Storage
 */
export const uploadInvoice = async (file: File, type: 'invoice' | 'boleto' | 'transfer', protocolId: string): Promise<string> => {
  const fileExt = file.name.split('.').pop() || 'bin';
  let subfolder: string;
  
  if (type === 'invoice') {
    subfolder = 'notas_fiscais';
  } else if (type === 'boleto') {
    subfolder = 'boletos';
  } else { // type === 'transfer'
    subfolder = 'transferencias';
  }
  
  // Tarefa 5: Usar protocolId (que agora é garantido) no path
  const safeFileName = `${subfolder}/${protocolId}/${Date.now()}_${Math.random().toString(36).substring(2, 9)}.${fileExt}`;

  const options = {
    cacheControl: '3600',
    upsert: false,
    contentType: file.type || undefined,
  };

  const { error } = await supabase.storage
    .from(STORAGE_BUCKET)
    .upload(safeFileName, file, options);

  if (error) {
    console.error('[storage-upload] Detailed Error:', error);
    throw new Error(error.message || 'Falha desconhecida no upload do Supabase Storage.');
  }

  const { data: publicUrlData } = supabase.storage
    .from(STORAGE_BUCKET)
    .getPublicUrl(safeFileName);

  return publicUrlData.publicUrl;
};

/**
 * Cria um registro inicial no banco de dados com status DRAFT, permitindo que o trigger gere o protocolo.
 * @returns O protocolo gerado pelo banco de dados, ou null em caso de falha.
 */
export const createDraftRequest = async (departmentId: string, authorizerId: string, paymentAccountId: string): Promise<string | null> => {
  // NÃO enviamos amount_cents nem payment_method, confiando que o DB aceita NULL/default para DRAFT
  const dbPayload = {
    status: 'draft',
    requester_name: 'Rascunho',
    requester_whatsapp: '(00) 00000-0000',
    department_id: departmentId,
    authorizer_id: authorizerId,
    due_date: new Date().toISOString().split('T')[0],
    payment_account_id: paymentAccountId,
    vendor_name: 'Rascunho',
    description: 'Rascunho de solicitação',
    invoice_commitment: false,
    agreed_terms: false,
    urgent: false,
  };

  try {
    const { data, error } = await supabase
      .from(TABLE_NAME)
      .insert([dbPayload])
      .select('protocol')
      .single();

    if (error) {
      // Log detalhado do erro do Supabase
      console.error('[createDraftRequest] Supabase DB Insert Error:', {
        message: error.message,
        details: error.details,
        hint: error.hint,
        status: error.status,
        payload: dbPayload // Log do payload que falhou
      });
      return null;
    }
    
    if (data?.protocol) {
      console.log(`[createDraftRequest] Protocol generated by DB: ${data.protocol}`);
      return data.protocol;
    }
    
    return null;
  } catch (e) {
    console.error("[createDraftRequest] Save failed (Exception)", e);
    return null;
  }
};

/**
 * Atualiza o registro DRAFT com a URL do anexo após um upload bem-sucedido.
 */
export const updateRequestAttachments = async (
  protocolId: string, 
  type: 'invoice' | 'boleto' | 'transfer', 
  url: string
): Promise<boolean> => {
  let payload: { [key: string]: string };
  
  if (type === 'invoice') {
    payload = { invoice_attachment_path: url };
  } else if (type === 'boleto') {
    payload = { boleto_attachment_path: url };
  } else { // type === 'transfer'
    payload = { transfer_attachment_path: url };
  }

  const { error } = await supabase
    .from(TABLE_NAME)
    .update(payload)
    .eq('protocol', protocolId);

  if (error) {
    console.error('[updateRequestAttachments] Supabase DB Update Error:', JSON.stringify(error, null, 2));
    return false;
  }
  return true;
};


/**
 * Finaliza a solicitação.
 */
export const submitRequest = async (
  data: CSPFormData, 
  requestId: string, 
  authorizerId: string, 
  paymentAccountId: string, 
  isUrgent: boolean
): Promise<boolean> => {
  
  const url_anexo = data.hasInvoice === 'yes' && data.invoiceUrl 
    ? data.invoiceUrl 
    : 'Pendente via WhatsApp';

  // Mapeamento do payment_method para minúsculas, conforme esperado pelo DB
  // Adicionando 'cash' como opção, caso seja implementado futuramente, mas mantendo o foco nos 3 principais.
  const mappedPaymentMethod = data.paymentMethod.toLowerCase().replace('transferência', 'transferencia');
  
  // amount_cents deve ser um número inteiro > 0
  const amountCents = parseInt(data.value);

  // Limpeza condicional de campos específicos para evitar vazamento
  const isTransfer = data.paymentMethod === 'Transferência';
  const isBoleto = data.paymentMethod === 'Boleto';
  const isPix = data.paymentMethod === 'PIX';

  const dbPayload = {
    requester_name: data.requesterName,
    requester_whatsapp: data.whatsapp,
    department_id: data.departmentId,
    description: data.description,
    due_date: data.dueDate,
    vendor_name: data.supplierName,
    amount_cents: amountCents, 
    payment_method: mappedPaymentMethod,
    
    // PIX
    pix_key: isPix ? data.pixKey : null,
    
    // Boleto
    boleto_attachment_path: isBoleto ? data.boletoUrl : null,
    
    // Transferência (NEW)
    transfer_bank: isTransfer ? data.transferBankName : null,
    transfer_account_type: isTransfer ? data.transferAccountType : null,
    transfer_agency: isTransfer ? data.transferAgency : null,
    transfer_account: isTransfer ? data.transferAccount : null,
    transfer_document: isTransfer ? data.transferCpfCnpj : null, // Mapeando para transfer_document
    transfer_favored_name: isTransfer ? data.transferBeneficiaryName : null, // Mapeando para transfer_favored_name
    transfer_attachment_path: isTransfer ? data.transferUrl : null, // Garantindo que o path seja salvo

    // Comuns
    status: 'pending' as RequestStatus, // Garantindo status 'pending'
    invoice_attachment_path: url_anexo,
    is_budget_specific: data.isSpecificBudget === 'yes',
    budget_id: null, 
    authorization_number: data.authNumber || null,
    authorizer_id: authorizerId,
    payment_account_id: paymentAccountId,
    agreed_terms: data.termsAccepted,
    urgent: isUrgent,
    invoice_commitment: data.invoiceSentViaWhatsapp,
  };

  // Validação e Log (Requisito)
  if (!requestId) {
    console.error('[submitRequest] Erro de validação: Protocolo (requestId) não fornecido.');
    return false;
  }
  if (!dbPayload.payment_method || dbPayload.amount_cents <= 0) {
    console.error('[submitRequest] Erro de validação: Método de pagamento ou valor inválido.', { method: dbPayload.payment_method, amount: dbPayload.amount_cents });
    return false;
  }

  // Logar o payload completo para conferência (Requisito)
  console.log('[submitRequest] Final Payload:', dbPayload);
  
  try {
    // Garantir que é um UPDATE no registro existente usando o protocolo
    const { error, status } = await supabase
      .from(TABLE_NAME)
      .update(dbPayload)
      .eq('protocol', requestId); // Filtro correto

    if (error) {
      // Log detalhado do erro do Supabase
      console.error('[submitRequest] Supabase DB Update Error (Final Submission):', {
        message: error.message,
        details: error.details,
        hint: error.hint,
        status: error.status,
        payload: dbPayload
      });
      return false;
    }

    return true;

  } catch (e) {
    console.error("Final submission failed (Exception)", e);
    return false;
  }
};

export const getRequestByProtocol = async (protocol: string): Promise<CSPRequest | null> => {
  const normalizedProtocol = protocol.trim().toUpperCase();
  console.log(`[API] Searching for protocol: ${normalizedProtocol}`);
  
  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select('*')
    .eq('protocol', normalizedProtocol)
    .single();

  if (error || !data) {
    console.error(`[API] Protocol search failed for ${normalizedProtocol}. Error:`, error);
    return null;
  }

  console.log(`[API] Protocol found: ${normalizedProtocol}. Data:`, data);

  return {
    id: data.protocol,
    requesterName: data.requester_name,
    whatsapp: data.requester_whatsapp,
    departmentId: data.department_id,
    authorizer: data.authorizer_id,
    dueDate: data.due_date,
    paymentAccount: data.payment_account_id,
    isSpecificBudget: data.is_budget_specific ? 'yes' : 'no',
    supplierName: data.vendor_name,
    value: data.amount_cents ? data.amount_cents.toString() : '0', // Adicionado fallback para '0'
    paymentMethod: data.payment_method || '', // Adicionado fallback para string vazia
    hasInvoice: data.invoice_attachment_path ? 'yes' : 'no',
    invoiceSentViaWhatsapp: data.invoice_commitment,
    description: data.description,
    termsAccepted: data.agreed_terms,
    createdAt: data.created_at,
    status: data.status as RequestStatus,
    invoiceUrl: data.invoice_attachment_path,
    boletoUrl: data.boleto_attachment_path,
    // NEW Transfer fields
    transferBankName: data.transfer_bank || '',
    transferAccountType: data.transfer_account_type || '',
    transferAgency: data.transfer_agency || '',
    transferAccount: data.transfer_account || '',
    transferCpfCnpj: data.transfer_document || '', // Mapeando de volta
    transferBeneficiaryName: data.transfer_favored_name || '', // Mapeando de volta
    transferUrl: data.transfer_attachment_path,
    history: []
  };
};

export const getRequests = async (): Promise<CSPRequest[]> => {
  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select('*')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching requests:', error);
    return [];
  }

  return data.map(req => ({
    id: req.protocol,
    requesterName: req.requester_name,
    whatsapp: req.requester_whatsapp,
    departmentId: req.department_id,
    authorizer: req.authorizer_id,
    dueDate: req.due_date,
    paymentAccount: req.payment_account_id,
    isSpecificBudget: req.is_budget_specific ? 'yes' : 'no',
    supplierName: req.vendor_name,
    value: req.amount_cents ? req.amount_cents.toString() : '0', // Adicionado fallback para '0'
    paymentMethod: req.payment_method || '', // Adicionado fallback para string vazia
    hasInvoice: req.invoice_attachment_path ? 'yes' : 'no',
    invoiceSentViaWhatsapp: req.invoice_commitment,
    description: req.description,
    termsAccepted: req.agreed_terms,
    createdAt: req.created_at,
    status: req.status as RequestStatus,
    boletoUrl: req.boleto_attachment_path,
    invoiceUrl: req.invoice_attachment_path,
    // NEW Transfer fields
    transferBankName: req.transfer_bank || '',
    transferAccountType: req.transfer_account_type || '',
    transferAgency: req.transfer_agency || '',
    transferAccount: req.transfer_account || '',
    transferCpfCnpj: req.transfer_document || '',
    transferBeneficiaryName: req.transfer_favored_name || '',
    transferUrl: req.transfer_attachment_path,
    history: []
  }));
};

export const updateRequestStatus = async (id: string, status: RequestStatus): Promise<boolean> => {
  const { error } = await supabase
    .from(TABLE_NAME)
    .update({ status })
    .eq('protocol', id);

  if (error) {
    console.error('Error updating status:', error);
    return false;
  }

  return true;
};