// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dtfynbxcbtpnamvzbpdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0ZnluYnhjYnRwbmFtdnpicGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxNjcwODMsImV4cCI6MjA4MTc0MzA4M30.TgIhhbquB9MM79q6OkkkIsIsMWP83h6WWeBuc69uVAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);